### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by meet447** [andradesavio9073/haruhi#48]
can it be hosted using vercel?

**Comment by meet447** [comment]
looking forward to the read me!

**Comment by andradesavio9073** [comment]
@meet447 I've updated the readme finally. it details most of the steps you would need to do to be able to deploy to Vercel. However, the Cors Proxy that I use is not amazingly documented as it's tailored to my needs. but it should be fairly easy to set up. just follow the .env.example in that repo. tho some things depend on how you are deploying it. GL

**Comment by meet447** [comment]
> @meet447 I've updated the readme finally. it details most of the steps you would need to do to be able to deploy to Vercel. However, the Cors Proxy that I use is not amazingly documented as it's tailored to my needs. but it should be fairly easy to set up. just follow the .env.example in that repo. tho some things depend on how you are deploying it. GL

Thankyou 🙏
